### ISSUE TITLE
JNI NewObjectV called with pending exception java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by capezzbr** [LiquidPlayer/LiquidCore#43]
### Details
- Using: `LiquidCore:0.4.4`
- Work on `LiquidCore:0.2.2`
- Tested on physical device and simulator

### Stack trace

```
Pending exception java.lang.NoSuchMethodError: no non-static method "Lorg/liquidplayer/javascript/JNIJSContextGroup;.<init>(J)V"
  at org.liquidplayer.javascript.JNIJSContextGroup org.liquidplayer.javascript.JNIJSContextGroup.create() (JNIJSContextGroup.java:-2)
  at void org.liquidplayer.javascript.JSContextGroup.<init>() (JSContextGroup.java:71)
  at void org.liquidplayer.javascript.JSContext.<init>() (JSContext.java:125)
  at void yapl.js.fusion.JavaScriptCore.JavascriptEngine.<init>() (JavascriptEngine.java:32)
  at yapl.js.fusion.FusionEngine yapl.js.fusion.FusionEngine.getJSEngine() (FusionEngine.java:15)

```

**Comment by ericwlange** [comment]
The native code is trying to instantiate a java object, but can't for some reason.  I can think of two reasons where you might see this:

1. There is some funny business with proguard -- does this happen if you have proguard disabled everywhere?  Proguard mangles symbols to prevent reverse engineering, but it is not smart enough to keep it from mangling symbols needed by native functions.  So I disabled it in LiquidCore, but if you have it in your project, maybe it is doing the same thing?
2. There are two versions of the library laying around in the project possibly?  (One pointing to 0.2.2 and one pointing to 0.4.4?) . I am not sure if this is possible without at least a warning, but this is off the top of my head.

I suggest you construct a test where you create an app from scratch that just loads the library and attempts to create a context.  Do you still get the same error?

**Comment by capezzbr** [comment]
Thanks for the help @ericwlange, I've added

```
-keep class org.liquidplayer.** { *; }
-keep interface org.liquidplayer.** { *; }
```

to my proguard file and it worked 👍
