### ISSUE TITLE
Android ndk r17 compile failed

### ISSUE THREAD

**Issue by chufuxi** [LiquidPlayer/LiquidCore#51]
LiquidCore: 0.4.6
ndk: r17

Compile Message:
FAILED: : && /Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi --gcc-toolchain=/Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/sysroot -fPIC -isystem /Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -fexceptions -Wall -Wextra -Wno-unused-parameter -fPIC -O3 -fno-omit-frame-pointer -fPIE -Wno-strict-aliasing -Wno-unused-variable -Wno-mismatched-tags -Wno-unused-result -fno-rtti -std=c++1y -DDEBUG -DNODE_ARCH="" -DNODE_PLATFORM="android" -DNODE_WANT_INTERNALS=1 -DV8_DEPRECATION_WARNINGS=1 -DNODE_SHARED_MODE -DNODE_USE_V8_PLATFORM=1 -DHAVE_INSPECTOR=0 -DV8_INSPECTOR_USE_STL=1 -DV8_INSPECTOR_USE_OLD_STL=1 -DHAVE_OPENSSL=1 -D__POSIX__ -DHTTP_PARSER_STRICT=0 -D_LARGEFILE_SOURCE -D_GLIBCXX_USE_C99_MATH -D_REENTRANT=1 -DSQLITE_DISABLE_LFS -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DJSCSHIM_IMPL -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/platforms/android-16/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -L/Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libliquidcore.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libliquidcore.so CMakeFiles/liquidcore.dir/Users/chufuxi/Development/opensource/LiquidCore/deps/node-sqlite3/src/database.cc.o CMakeFiles/liquidcore.dir/Users/chufuxi/Development/opensource/LiquidCore/deps/node-sqlite3/src/node_sqlite3.cc.o CMakeFiles/liquidcore.dir/Users/chufuxi/Development/opensource/LiquidCore/deps/node-sqlite3/src/statement.cc.o CMakeFiles/liquidcore.dir/Users/chufuxi/Development/opensource/LiquidCore/deps/jscshim/JSCShim.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/Common/ContextGroup.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/Common/JSContext.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/Common/JSValue.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/Common/LoopPreserver.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JNI/JNI_JSContext.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JNI/JNI_JSContextGroup.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JNI/JNI_JSObject.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JNI/JNI_JSValue.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JNI/JNI_LoopPreserver.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JNI/JNI_OnLoad.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JNI/JNIJSException.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JNI/JSFunction.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/JSC_JSBase.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/JSC_JSContext.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/JSC_JSContextGroup.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/JSC_JSObject.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/JSC_JSString.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/JSC_JSValue.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/ObjectData.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/OpaqueJSClass.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/OpaqueJSContext.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/OpaqueJSContextGroup.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/OpaqueJSString.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/JSC/OpaqueJSValue.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/node/JNI_Process.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/node/nodedroid_file.cc.o CMakeFiles/liquidcore.dir/src/main/cpp/node/NodeInstance.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/node/process_wrap.cc.o CMakeFiles/liquidcore.dir/src/main/cpp/node/sqlite3_shim.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/androidTest/testapi.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/androidTest/CustomGlobalObjectClassTest.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/androidTest/JSNode.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/androidTest/JSNodeList.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/androidTest/Node.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/androidTest/NodeList.cpp.o CMakeFiles/liquidcore.dir/src/main/cpp/androidTest/minidom.cpp.o  ../../../../../deps/node-8.9.3/prebuilt/32bit/symbols/armeabi-v7a/libnode.so -llog -latomic -lm "/Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_static.a" "/Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++abi.a" "/Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libandroid_support.a" "/Users/chufuxi/Development/android-sdk-macosx-google/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libunwind.a" "-ldl" && :
  /Users/chufuxi/Development/opensource/LiquidCore/LiquidCoreAndroid/src/main/cpp/node/NodeInstance.cpp:810: error: undefined reference to 'node::SafeGetenv(char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >*)'
  /Users/chufuxi/Development/opensource/LiquidCore/LiquidCoreAndroid/src/main/cpp/node/NodeInstance.cpp:811: error: undefined reference to 'node::crypto::UseExtraCaCerts(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

**Comment by ericwlange** [comment]
This one is stumping me at the moment.  This will have to stay <= r16 for the time being.

**Comment by ericwlange** [comment]
This is now working in 0.5.0-experimental-4.
